language: go

dist: trusty

addons:
  apt:
    packages:
      - gccgo-6
    sources:
      - ubuntu-toolchain-r-test

go:
  - 1.x
  - 1.6
  - 1.7.x
  - master

script:
  - gccgo-6 --version
  - go get -d ./...
  - make build-all
