language: go

dist: xenial

addons:
  apt:
    packages:
      - gccgo-6
    sources:
      - ubuntu-toolchain-r-test

env:
  - GO111MODULE=on

install: true

matrix:
  include:
    - go: 1.6.x
    - go: 1.7.x
    - go: 1.8.x
    - go: 1.9.x
    - go: 1.10.x
    - go: 1.11.x
    - go: 1.12.x
    - go: 1.13.x
    - go: tip
  allow_failures:
    - go: 1.6.x
    - go: tip
    
before_script:
  - gccgo-6 --version
  - make build
  
script:
  - ./bin/statsd-http-proxy --version
