language: go

dist: bionic

addons:
  apt:
    packages:
      - gccgo-6
    sources:
      - ubuntu-toolchain-r-test

install: true

matrix:
  include:
    - go: 1.6.x
      env:
        - GOPATH: ${TRAVIS_BUILD_DIR}
    - go: 1.7.x
      env:
        - GOPATH: ${TRAVIS_BUILD_DIR}
    - go: 1.8.x
      env:
        - GOPATH: ${TRAVIS_BUILD_DIR}
    - go: 1.9.x
      env:
        - GOPATH: ${TRAVIS_BUILD_DIR}
    - go: 1.10.x
      env:
        - GOPATH: ${TRAVIS_BUILD_DIR}
    - go: 1.11.x
      env: 
        - GO111MODULE=on
    - go: 1.12.x
      env: 
        - GO111MODULE=on
    - go: 1.13.x
    - go: tip
  allow_failures:
    - go: 1.6.x
    - go: tip
    
before_script:
  - gccgo-6 --version
  - make build
  
script:
  - ./bin/statsd-http-proxy --version
